---
- block:
    - name: Install dependencies
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install elastalert
      pip:
        name: elastalert
        executable: pip3

    - name: Create directories if it does not exist
      file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ rules_folder }}'
        - '{{ main_folder }}'

    - name: Git checkout from elastalert repo
      git:
        repo: '{{ elastalert_repo }}'
        dest: '{{ temp_folder }}'
    
    - name: Install requirements for python
      pip:
        requirements: '{{ temp_folder }}/requirements.txt'
        executable: pip3

    - name: Place config file with settings
      template:
        src: config.yaml.j2
        dest: '{{ main_folder }}/config.yaml'
        owner: root
        group: root
        mode: 0644

    - name: Place rule to rules directory
      template:
        src: rule.yaml.j2
        dest: '{{ rules_folder }}/{{ item.value.name }}.yaml'
        owner: root
        group: root
        mode: 0644
      with_dict: '{{ rules_config }}'

    - name: Place service file
      template:
        src: elastalert.service.j2
        dest: /etc/systemd/system/elastalert.service.j2
        owner: root
        group: root
        mode: 0644

    - name: Start & enable elastalert service
      systemd:
        name: elastalert
        state: started
        daemon-reload: yes
        
  become: true